dist: bionic
language: generic

if: branch = master

env:
  - PLATFORMS="linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6"

services: docker
install:
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker run --rm --privileged -d --name buildkitd moby/buildkit:latest
  - sudo docker cp buildkitd:/usr/bin/buildctl /usr/local/bin
  - export BUILDKIT_HOST="docker-container://buildkitd"

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script: |
  buildctl build \
    --progress=plain \
    --frontend=dockerfile.v0 \
    --local context=. --local dockerfile=. \
    --opt filename=Dockerfile \
    --opt platform=$PLATFORMS \
    --opt target=it-works \
    --output type=image,name=docker.io/robertgzr/it-works:latest,push=true

  buildctl build \
    --progress=plain \
    --frontend=dockerfile.v0 \
    --local context=. --local dockerfile=. \
    --opt filename=Dockerfile \
    --opt platform=$PLATFORMS \
    --opt target=idle \
    --output type=image,name=docker.io/robertgzr/idle:latest,push=true

after_failure:
  - buildctl debug workers ls
  - docker logs buildkitd
