# This dockerfile can be used to build armv7hf artifacts
# from x86_64 host machines:
# usage: docker run <this> make go

FROM balenalib/armv7hf-alpine-golang

# Enable QEMU emulation
ENTRYPOINT [ "qemu-arm-static", "-execve", "/bin/ash", "-c" ]
SHELL      [ "qemu-arm-static", "-execve", "/bin/ash", "-c" ]

ENV GOARCH arm
ENV GOARM 7

RUN apk --no-cache add -U \
        git \
        make

COPY . /src

WORKDIR /src
